{{- if .Values.coreweave.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rhai-coreweave-cloud-manager-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - namespaces
      - secrets
      - serviceaccounts
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cert-manager.io
    resources:
      - certificates
      - clusterissuers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - infrastructure.opendatahub.io
    resources:
      - coreweavekubernetesengines
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - infrastructure.opendatahub.io
    resources:
      - coreweavekubernetesengines/finalizers
    verbs:
      - update
  - apiGroups:
      - infrastructure.opendatahub.io
    resources:
      - coreweavekubernetesengines/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - kuadrant.io
    resources:
      - kuadrants
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - operator.openshift.io
    resources:
      - certmanagers
      - leaderworkersetoperators
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
      - rolebindings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resourceNames:
      - authorino-authconfig-editor-role
      - authorino-authconfig-viewer-role
      - authorino-manager-k8s-auth-role
      - authorino-manager-role
      - authorino-operator-clusterrole
      - dns-operator-controller-manager-clusterrole
      - dns-operator-metrics-reader
      - dns-operator-remote-cluster-role
      - kuadrant-operator-controller-manager-clusterrole
      - kuadrant-operator-controller-manager-clusterrole-1
      - limitador-operator-controller-manager-clusterrole
      - limitador-operator-metrics-reader
    resources:
      - clusterroles
    verbs:
      - bind
      - delete
      - escalate
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resourceNames:
      - metrics-reader
    resources:
      - clusterroles
    verbs:
      - bind
      - delete
      - escalate
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resourceNames:
      - openshift-lws-operator-clusterrole
    resources:
      - clusterroles
    verbs:
      - bind
      - delete
      - escalate
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resourceNames:
      - servicemesh-operator3-clusterrole
      - servicemeshoperator3-metrics-reader
    resources:
      - clusterroles
    verbs:
      - bind
      - delete
      - escalate
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
    verbs:
      - create
      - list
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resourceNames:
      - authorino-operator-role
      - dns-operator-controller-manager-role
      - kuadrant-operator-controller-manager-role
      - kuadrant-operator-controller-manager-role-1
      - limitador-operator-controller-manager-role
    resources:
      - roles
    verbs:
      - bind
      - delete
      - escalate
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resourceNames:
      - openshift-lws-operator-role
    resources:
      - roles
    verbs:
      - bind
      - delete
      - escalate
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resourceNames:
      - servicemesh-operator3-role
    resources:
      - roles
    verbs:
      - bind
      - delete
      - escalate
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - sailoperator.io
    resources:
      - istios
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
{{- end }}
